### ISSUE TITLE
no implicit conversion of nil into String in sys-proctable 1.1.2

### ISSUE THREAD

**Issue by djberg96** [djberg96/sys-proctable#56]
Ruby 2.3.1 on El Capitan:

```
irb(main):002:0> Sys::ProcTable.ps
TypeError: no implicit conversion of nil into String
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:320:in `+'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:320:in `block in get_cmd_args_and_env'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:319:in `times'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:319:in `get_cmd_args_and_env'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:189:in `block in ps'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:174:in `each'
	from /Users/djberge/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sys-proctable-1.1.2-universal-darwin/lib/darwin/sys/proctable.rb:174:in `ps'
	from (irb):2
	from /Users/djberge/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

The other issue is that it's hitting the installed gem instead of using the local code.

**Comment by djberg96** [comment]
Some details. Seems to be choking on a postgres process. I stuck in some debug prints that show the argc value, the exe value and the contents of the array after deleting empty strings:

```
ARGC: 3
EXE: /usr/local/opt/postgresql/bin/postgres
["/usr/local/opt/postgresql/bin/postgres", "postgres: checkpointer process   ", "XPC_FLAGS=0x1", "\xFF\xBF", "/usr/local/opt/postgresql/bin/postgres"]
["postgres: checkpointer process   ", "XPC_FLAGS=0x1"]
```

So, despite the fact that argc is returning 3, the result is that we only get an array of 2 values, and so it chokes trying to append nil.

**Comment by djberg96** [comment]
@bmathwig, any thoughts as to why get a bogus argc value there?

**Comment by djberg96** [comment]
I saw this comment from another lib at https://github.com/deric/libprocess/blob/master/3rdparty/stout/include/stout/os/osx.hpp:

```
  // In practice it appeared that we might get an 'argc'
  // which is greater than 'tokens.size()' which caused us
  // to get an invalid iterator from 'tokens.begin() +
  // argc', thus we now check that condition here.
  if (static_cast<size_t>(argc) <= tokens.size()) {
    tokens.erase(tokens.begin() + argc, tokens.end());
  }
```

**Comment by djberg96** [comment]
How does this look for a patch?

      if argc > array.size
        array.delete_if{ |e| e.include?("=") }
        argc = array.size
      end

**Comment by djberg96** [comment]
Well, I went with that. It works. We can always revisit if it needs tweaking.
